root: ../../data
dataset: Amazon2014Beauty_550_LOU
tasktag: NEXTITEM

num_codewords: 256
num_codebooks: 3
codebook_dim: 32
hidden_dims: 256,128,64
gradient_estimator: rotation
# gumbel softmax
gumbel_temperature: 0.05
apply_kmeans_init: True
apply_sim_vq: False
commit_weight: 0.3
dropout_rate: 0.2

epochs: 100
batch_size: 64
lr: 1.e-3
weight_decay: 1.e-2

sem_feat_file: sentence-t5-xl_title_categories_brand.pkl