root: ../../data
dataset: Amazon2014Beauty_550_LOU

maxlen: 20
num_heads: 2
embedding_dim: 64
hidden_size: 256

num_qformer_blocks: 2
qformer_dropout_rate: 0.1

num_encoder_blocks: 2
encoder_dropout_rate: 0.3

epochs: 100
batch_size: 512
optimizer: AdamW
lr: 1.e-3
weight_decay: 1.e-8
num_negs: 49
weight4mlm: 0.1
weight4cl: 0.5
mask_ratio: 0.2

sem_id_ckpt: product_12_256.pkl
tfiles: sentence-t5-xl_brand.pkl,sentence-t5-xl_categories.pkl,sentence-t5-xl_title.pkl

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10